packages:
  - "apps/*"
  - "packages/*"

packageExtensions:
  "@huggingface/transformers@4.2.0":
    dependencies:
      onnxruntime-common: 1.24.0-dev.20251116-b39e144322
  "@tiptap/y-tiptap@3.0.6":
    dependencies:
      prosemirror-transform: 1.12.0
