// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const ACCENT_DARK = {
  primary: 'var(--ij-accent)',
  secondary: 'var(--ij-accent-hover)',
  tertiary: 'var(--ij-selection)',
  quaternary: 'var(--ij-selection-inactive)',
  accent3570: 'var(--ij-accent)',
  accent4060: 'var(--ij-accent-hover)',
  accent1: 'var(--ij-blue-1)',
  accent2: 'var(--ij-blue-2)',
  accent3: 'var(--ij-blue-3)',
  accent4: 'var(--ij-blue-4)',
  accent5: 'var(--ij-blue-5)',
  accent6: 'var(--ij-blue-6)',
  accent7: 'var(--ij-blue-7)',
  accent8: 'var(--ij-blue-8)',
  accent9: 'var(--ij-blue-9)',
  accent10: 'var(--ij-blue-10)',
  accent11: 'var(--ij-blue-11)',
  accent12: 'var(--ij-blue-11)',
};
