// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const BACKGROUND_DARK = {
  noisy: 'transparent',
  primary: 'var(--ij-editor)',
  secondary: 'var(--ij-chrome)',
  tertiary: 'var(--ij-raised)',
  quaternary: 'var(--ij-tier-floating)',
  invertedPrimary: 'var(--ij-ink)',
  invertedSecondary: 'var(--ij-ink-info)',
  danger: 'var(--ij-error-bg)',
  transparent: {
    primary: 'var(--ij-tier-scrim)',
    secondary: 'var(--ij-tier-scrim)',
    strong: 'var(--ij-pressed-overlay)',
    medium: 'var(--ij-hover-overlay)',
    light: 'var(--ij-hover-surface)',
    lighter: 'var(--ij-keyline-decorative)',
    danger: 'var(--ij-error-bg)',
    blue: 'var(--ij-selection)',
    orange: 'var(--ij-warn-bg)',
    success: 'var(--ij-ok-bg)',
  },
  overlayPrimary: 'var(--ij-tier-scrim)',
  overlaySecondary: 'var(--ij-tier-scrim)',
  overlayTertiary: 'var(--ij-tier-scrim)',
  radialGradient: 'radial-gradient(50% 62.62% at 50% 0%, var(--ij-tier-raised) 0%, var(--ij-tier-floating) 100%)',
  radialGradientHover: 'radial-gradient(76.32% 95.59% at 50% 0%, var(--ij-tier-floating) 0%, var(--ij-raised) 100%)',
  primaryInverted: 'var(--ij-ink)',
  primaryInvertedHover: 'var(--ij-ink-info)',
};
