// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const BLUR_DARK = {
  light: 'blur(6px) saturate(200%) contrast(100%) brightness(130%)',
  medium: 'blur(12px) saturate(200%) contrast(100%) brightness(130%)',
  strong: 'blur(20px) saturate(200%) contrast(100%) brightness(130%)',
};
