// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const BORDER_LIGHT = {
  color: {
    strong: 'var(--ij-control-border)',
    medium: 'var(--ij-divider)',
    light: 'var(--ij-seam)',
    secondaryInverted: 'var(--ij-ink-info)',
    inverted: 'var(--ij-ink)',
    danger: 'var(--ij-error)',
    blue: 'var(--ij-accent)',
    transparentStrong: 'var(--ij-keyline-decorative)',
  },
  radius: {
    xs: 'var(--radius-chip, 4px)',
    sm: 'var(--radius-chip, 4px)',
    md: 'var(--radius-control, 7px)',
    smRound: 'var(--radius-chip, 4px)',
    mdRound: 'var(--radius-control, 7px)',
    lg: 'var(--radius-sunken, 10px)',
    xl: 'var(--ij-radius-lg)',
    xxl: 'var(--ij-radius-xl)',
    pill: '999px',
    rounded: '100%',
  },
};
