// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const BOX_SHADOW_DARK = {
  color: 'var(--ij-tier-scrim)',
  light: 'var(--shadow-lifted, 0 1px 2px rgb(0 0 0 / 0.04), 0 1px 6px rgb(0 0 0 / 0.03))',
  strong: 'var(--shadow-lifted, 0 1px 2px rgb(0 0 0 / 0.04), 0 1px 6px rgb(0 0 0 / 0.03))',
  underline: 'var(--shadow-docked-right, -1px 0 3px rgb(0 0 0 / 0.04))',
  superHeavy: 'var(--shadow-lifted, 0 1px 2px rgb(0 0 0 / 0.04), 0 1px 6px rgb(0 0 0 / 0.03))',
};
