// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const CODE_LIGHT = {
  text: {
    gray: 'var(--ij-ink-info)',
    sky: 'var(--ij-link)',
    pink: 'var(--ij-room)',
    orange: 'var(--ij-agent)',
    green: 'var(--ij-memory)',
  },
  font: {
    family: 'var(--ij-font-mono)',
  },
};
