// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

import { MAIN_COLORS_DARK } from './MainColorsDark';
import { SECONDARY_COLORS_DARK } from './SecondaryColorsDark';
import { TRANSPARENT_COLORS_DARK } from './TransparentColorsDark';

export const COLOR_DARK = {
  ...MAIN_COLORS_DARK,
  ...SECONDARY_COLORS_DARK,
  transparent: TRANSPARENT_COLORS_DARK,
};
