// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

import { MAIN_COLORS_LIGHT } from './MainColorsLight';
import { SECONDARY_COLORS_LIGHT } from './SecondaryColorsLight';
import { TRANSPARENT_COLORS_LIGHT } from './TransparentColorsLight';

export const COLOR_LIGHT = {
  ...MAIN_COLORS_LIGHT,
  ...SECONDARY_COLORS_LIGHT,
  transparent: TRANSPARENT_COLORS_LIGHT,
};
