// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const FONT_DARK = {
  color: {
    primary: 'var(--ij-ink)',
    secondary: 'var(--ij-ink-info)',
    tertiary: 'var(--ij-ink-disabled)',
    light: 'var(--ij-ink-disabled)',
    extraLight: 'var(--ij-gray-7)',
    inverted: 'var(--ij-editor)',
    danger: 'var(--ij-error)',
  },
  size: {
    xxs: '0.625rem',
    xs: '0.85rem',
    sm: '0.92rem',
    md: '1rem',
    lg: '1.23rem',
    xl: '1.54rem',
    xxl: '1.85rem',
  },
  weight: {
    regular: 400,
    medium: 500,
    semiBold: 600,
  },
  family: 'var(--ij-font-ui)',
};
