// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const GRAY_SCALE_LIGHT = {
  gray1: 'var(--ij-gray-14)',
  gray2: 'var(--ij-gray-13)',
  gray3: 'var(--ij-gray-12)',
  gray4: 'var(--ij-gray-11)',
  gray5: 'var(--ij-gray-10)',
  gray6: 'var(--ij-gray-9)',
  gray7: 'var(--ij-gray-8)',
  gray8: 'var(--ij-gray-7)',
  gray9: 'var(--ij-gray-6)',
  gray10: 'var(--ij-gray-5)',
  gray11: 'var(--ij-gray-3)',
  gray12: 'var(--ij-gray-2)',
};
