// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const GRAY_SCALE_DARK_ALPHA = {
  gray1: 'color-mix(in oklab, var(--ij-ink-bright) 3.1%, transparent)',
  gray2: 'color-mix(in oklab, var(--ij-ink-bright) 5.9%, transparent)',
  gray3: 'color-mix(in oklab, var(--ij-ink-bright) 4.7%, transparent)',
  gray4: 'color-mix(in oklab, var(--ij-ink-bright) 7.1%, transparent)',
  gray5: 'color-mix(in oklab, var(--ij-ink-bright) 10.2%, transparent)',
  gray6: 'color-mix(in oklab, var(--ij-ink-bright) 11.4%, transparent)',
  gray7: 'color-mix(in oklab, var(--ij-ink-bright) 14.1%, transparent)',
  gray8: 'color-mix(in oklab, var(--ij-ink-bright) 22%, transparent)',
  gray9: 'color-mix(in oklab, var(--ij-ink-bright) 42.7%, transparent)',
  gray10: 'color-mix(in oklab, var(--ij-ink-bright) 47.8%, transparent)',
  gray11: 'color-mix(in oklab, var(--ij-ink-bright) 56.5%, transparent)',
  gray12: 'color-mix(in oklab, var(--ij-ink-bright) 91%, transparent)',
};
