// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const ILLUSTRATION_ICON_LIGHT = {
  color: {
    blue: 'var(--ij-accent)',
    gray: 'var(--ij-ink-disabled)',
  },
  fill: {
    blue: 'var(--ij-selection)',
    gray: 'var(--ij-raised)',
  },
};
