// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const MAIN_COLORS_LIGHT = {
  red: 'oklch(63.00% 0.1200 25.0)',
  ruby: 'oklch(63.00% 0.1200 12.0)',
  crimson: 'oklch(63.00% 0.1200 0.0)',
  tomato: 'oklch(63.00% 0.1200 35.0)',
  orange: 'oklch(63.00% 0.1200 60.0)',
  amber: 'oklch(63.00% 0.1200 85.0)',
  yellow: 'oklch(63.00% 0.1200 100.0)',
  lime: 'oklch(63.00% 0.1200 125.0)',
  grass: 'oklch(63.00% 0.1200 140.0)',
  green: 'oklch(63.00% 0.1200 150.0)',
  jade: 'oklch(63.00% 0.1200 165.0)',
  mint: 'oklch(63.00% 0.1200 175.0)',
  turquoise: 'oklch(63.00% 0.1200 195.0)',
  cyan: 'oklch(63.00% 0.1200 220.0)',
  sky: 'oklch(63.00% 0.1200 235.0)',
  blue: 'oklch(63.00% 0.1200 258.0)',
  iris: 'oklch(63.00% 0.1200 275.0)',
  violet: 'oklch(63.00% 0.1200 295.0)',
  purple: 'oklch(63.00% 0.1200 310.0)',
  plum: 'oklch(63.00% 0.1200 330.0)',
  pink: 'oklch(63.00% 0.1200 350.0)',
  bronze: 'oklch(63.00% 0.1200 45.0)',
  gold: 'oklch(63.00% 0.1200 90.0)',
  brown: 'oklch(63.00% 0.1200 55.0)',
  gray: 'var(--ij-gray-9)',
};
