// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

export const SNACK_BAR_DARK = {
  success: {
    color: 'var(--ij-ok)',
    backgroundColor: 'var(--ij-ok-bg)',
  },
  error: {
    color: 'var(--ij-error)',
    backgroundColor: 'var(--ij-error-bg)',
  },
  warning: {
    color: 'var(--ij-warn)',
    backgroundColor: 'var(--ij-warn-bg)',
  },
  info: {
    color: 'var(--ij-accent)',
    backgroundColor: 'var(--ij-selection)',
  },
  default: {
    color: 'var(--ij-ink)',
    backgroundColor: 'var(--ij-hover-surface)',
  },
};
