// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run `npm run generate:theme`.

import { ANIMATION } from './Animation';
import { ICON } from './Icon';
import { MODAL } from './Modal';
import { TEXT } from './Text';

export const THEME_COMMON = {
  icon: ICON,
  modal: MODAL,
  text: TEXT,
  animation: ANIMATION,
  spacingMultiplicator: 4,
  spacing: (...args: number[]) =>
    args.map((multiplicator) => `${multiplicator * 4}px`).join(' '),
  betweenSiblingsGap: 'var(--rec-sibling-gap)',
  table: {
    horizontalCellMargin: 'var(--rec-cell-margin)',
    checkboxColumnWidth: 'var(--rec-utility-col)',
    horizontalCellPadding: 'var(--rec-cell-pad)',
  },
  sidePanelWidth: 'var(--rec-side-panel)',
  clickableElementBackgroundTransition:
    'var(--rec-clickable-transition)',
  lastLayerZIndex: 2147483647,
  buttons: {
    secondaryTextColor: 'var(--ij-ink-info)',
  },
};
