// SOURCING: rustyred-thg-programmable-graph.
// GENERATED FROM: Theorem/rustyredcore_THG/crates/rustyred-thg-programmable-graph.
// SOURCE COMMIT: 84f35a121
// Generated by the Rust-owned export_program_contracts binary.
// Do not hand-edit. Run `pnpm --filter @commonplace/program-contracts generate`.

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type Cardinality = "one" | "many";

export type FieldType = { "kind": "text" } | { "kind": "long_text" } | { "kind": "integer" } | { "kind": "number" } | { "kind": "boolean" } | { "kind": "timestamp" } | { "kind": "date" } | { "kind": "uuid" } | { "kind": "json" } | { "kind": "enum", variants: Array<string>, } | { "kind": "vector", dim: number, } | { "kind": "geometry" } | { "kind": "relation", target_object_type_id: string, cardinality: Cardinality, };

export type ProviderFacet = { "kind": "native-view",
/**
 * Relation the native-views surface serves this type from. `None`
 * means the surface resolves it from `node_label`.
 */
relation?: string | null, } | { "kind": "declared-record" } | { "kind": "derived-program", program_id: string, } | { "kind": "connector", connector_id: string, };

export type ColumnSchema = { name: string, data_type: FieldType, nullable: boolean, };

export type ColumnSet = { "kind": "undetermined" } | { "kind": "determined", columns: Array<ColumnSchema>, };

export type CardinalityClass = "one" | "bounded" | "unbounded";

export type RowCountEstimateClass = { "kind": "unknown" } | { "kind": "exact", rows: number, } | { "kind": "at_most", rows: number, } | { "kind": "at_least", rows: number, } | { "kind": "order_of_magnitude", log10: number, };

export type ColumnContract = { columns: ColumnSet, cardinality: CardinalityClass, row_count_estimate: RowCountEstimateClass, };

export type ContractCapability = {
/**
 * Capability name (must be a valid MCP tool name).
 */
name: string,
/**
 * Human-readable description.
 */
description: string,
/**
 * Input schema (JSON Schema for MCP tool input).
 */
input_schema: JsonValue,
/**
 * Whether this capability has side effects.
 */
has_side_effects: boolean, };

export type BlockContract = {
/**
 * Unique contract identifier.
 */
id: string,
/**
 * Human-readable contract name.
 */
name: string,
/**
 * Contract version.
 */
version: string,
/**
 * Description of what this contract provides.
 */
description: string,
/**
 * The capabilities this contract grants.
 */
capabilities: Array<ContractCapability>, };

export type DataPlane = "tenant_graph" | "datawave" | "rusty_web";

export type DataSelector = { plane: DataPlane, label: string, predicates: { [key in string]: JsonValue }, };

export type ProgramPort = { id: string, shape_id: string,
/**
 * Snapshot of the resolved shape's tabular contract at compose time.
 * Included in [`ProgramDefinition::content_id`] so schema changes change
 * program identity. `None` keeps legacy non-tabular ports.
 */
column_contract?: ColumnContract | null, };

export type SentinelWatch = { label?: string | null, property?: string | null, };

export type ProgramNodeKind = { "kind": "source", selector: DataSelector, } | { "kind": "sentinel", question: string, watch: SentinelWatch, target_derivation_id: string, } | { "kind": "rule", expression_root: string, } | { "kind": "stochastic", affordance_id: string, } | { "kind": "verify", verifier_id: string, } | { "kind": "fold", target_derivation_id: string, } | { "kind": "human_input", prompt: string, coordination_stream: string, } | { "kind": "sink", sink_id: string, asserts: boolean, effect: SinkEffect, };

export type ProgramNode = { id: string, block_id: string, contract: BlockContract, inputs: Array<ProgramPort>, outputs: Array<ProgramPort>, bypassed: boolean, muted: boolean, station?: ProgramStationFields | null, } & ({ "kind": "source", selector: DataSelector, } | { "kind": "sentinel", question: string, watch: SentinelWatch, target_derivation_id: string, } | { "kind": "rule", expression_root: string, } | { "kind": "stochastic", affordance_id: string, } | { "kind": "verify", verifier_id: string, } | { "kind": "fold", target_derivation_id: string, } | { "kind": "human_input", prompt: string, coordination_stream: string, } | { "kind": "sink", sink_id: string, asserts: boolean, effect: SinkEffect, });

export type ProgramStationHeadRole = "executor" | "verifier" | "peer_implementer";

export type ProgramBindingPresetHead = { head_id: string, provider: string, model: string, role: ProgramStationHeadRole, };

export type ProgramBindingPreset = { preset_id: string, display_name: string, binding_ref: string, topology: ProgramStationTopology, capability_pack: Array<string>, budget_units: number, sealed: boolean, owner_principal_id?: string | null, roster?: Array<ProgramBindingPresetHead> | null, };

export type ProgramStationTopology = "solo" | "pair" | "peer";

export type ProgramStationFields = { preset_id: string, binding_ref: string, capability_pack: Array<string>, budget_units: number, topology: ProgramStationTopology, compiled_topology: ProgramStationTopology, sealed: boolean, };

export type StationDropRequest = { program_id: string, node_id: string, preset_id: string, requested_topology?: ProgramStationTopology | null, };

export type StationDropReceipt = { program_id: string, node_id: string, station: ProgramStationFields, };

export type ProgramEdge = { id: string, from_node: string, from_port: string, to_node: string, to_port: string, };

export type ProgramTrigger = { "kind": "graph_change", labels: Array<string>, properties: Array<string>, } | { "kind": "schedule", cron: string, } | { "kind": "coordination_stream", stream: string, };

export type BudgetPolicy = { max_invocations: number, window_seconds: number, max_cost_microunits: number, };

export type ApprovalMode = "require_each_run" | "require_side_effects" | "preapproved_within_grants";

export type ProgramAuthority = "advisory" | "authorization_commit";

export type SinkEffect = "advisory" | "external";

export type ApprovalPolicy = { mode: ApprovalMode, grant_ids: Array<string>, };

export type EvolutionPolicy = { objective: string, metric_id: string, correctness_anchor_node_ids: Array<string>, evolvable_node_ids: Array<string>, evolvable_edge_ids: Array<string>, };

export type ProgramDefinition = { tenant_id: string, name: string, intent: string, authority: ProgramAuthority, graph_lisp_root?: string | null, parent_program_id?: string | null, trigger: ProgramTrigger, budget: BudgetPolicy, approval: ApprovalPolicy, nodes: Array<ProgramNode>, edges: Array<ProgramEdge>, evolution?: EvolutionPolicy | null, metadata: { [key in string]: JsonValue }, };

export type CatalogSource = { library: string, version: string, generator?: string | null, };

export type FitStateClass = "stateless" | "fitted";

export type CatalogLifecycle = "stable" | "beta" | "legacy";

export type CatalogNodeKind = "source" | "sentinel" | "rule" | "stochastic" | "verify" | "fold" | "sink" | "human_input";

export type CatalogAuthoringRuntime = "quick_js" | "wasm";

export type ShapeSpec = { "kind": "variables_declared_at_init" } | { "kind": "preserve_or_replace_variables" } | { "kind": "preserve_columns" } | { "kind": "graph_nodes" } | { "kind": "node_scores" } | { "kind": "tabular_any" } | { "kind": "tabular_pair" } | { "kind": "join_columns" } | { "kind": "function", name: string, } | { "kind": "other" };

export type CatalogEntry = { id: string, group: string, class_name?: string | null, module?: string | null, source: CatalogSource, fit_state: FitStateClass, input_shape: ShapeSpec, output_shape: ShapeSpec, lifecycle: CatalogLifecycle, node_kind?: CatalogNodeKind | null, authoring_runtime?: CatalogAuthoringRuntime | null, contract?: BlockContract | null, input_ports: Array<ProgramPort>, output_ports: Array<ProgramPort>, published_program_id?: string | null, };

export type SchemaMismatch = { column: string, producer_shape: string, consumer_shape: string, producer_detail: string, consumer_detail: string, };

export type EdgeSchemaStatus = "compatible" | "undetermined" | { "mismatch": SchemaMismatch };

export type ProgramRefusal = { code: string, message: string, node_ids?: Array<string>, };

export type ValidationCheck = { requirement: string, passed: boolean, };

export type ValidationReceipt = { program_id: string, checks: Array<ValidationCheck>, };

export type ProcessLiveness = "dormant" | "running" | "verifying" | "parked" | "refused" | "failed";

export type CanvasNode = { node_id: string, block_id: string, contract_id: string, process_kind: string, input_shapes: Array<string>, output_shapes: Array<string>, liveness: ProcessLiveness, };

export type CanvasEdge = { edge_id: string, from_node: string, from_port: string, to_node: string, to_port: string, shape_id: string, };

export type CanvasProjection = { schema: string, program_id: string, nodes: Array<CanvasNode>, edges: Array<CanvasEdge>, };

export type CompilerProposal = { source_intent: string, compiler_id: string, compiler_receipt_id: string, proposed_program: ProgramDefinition, };

export type ProgramDiff = { node_ids_only_in_left: Array<string>, node_ids_only_in_right: Array<string>, edge_ids_only_in_left: Array<string>, edge_ids_only_in_right: Array<string>, changed_node_ids: Array<string>, metadata_changed: boolean, authority_changed: boolean, };

export type DataTypeBadge = { "kind": "none" } | { "kind": "undetermined" } | { "kind": "determined", column_count: number, types: Array<string>, };

export type FitState = { model_artifact_node_id: string, training_manifest_id: string,
/**
 * Observed levels / feature names produced by fit (e.g. OneHot categories).
 */
observed_levels: Array<string>,
/**
 * Optional variable the transform was fitted on.
 */
variable?: string | null, metadata: { [key in string]: JsonValue }, };

export type ProgramRunEventKind = "node_started" | "node_output_chunk" | "node_token_chunk" | "node_verifying" | "node_finished" | "node_error" | "node_parked" | "execution_cached" | "node_refused";

export type ProgramValueRef = { "storage": "inline", value: JsonValue, } | { "storage": "spilled", fetch_handle: string, digest: string, original_bytes: number, summary: JsonValue, };

export type PinnedNodeValue = { value: ProgramValueRef, value_hash: string, pinned_at_ms: number, };

export type ProgramRunOptions = { invocation_id?: string | null, inputs: { [key in string]: JsonValue }, tweaks: { [key in string]: JsonValue }, pinned_nodes: { [key in string]: PinnedNodeValue }, human_answers: { [key in string]: JsonValue }, };

export type ProgramNodeInspection = { node_id: string, inputs?: ProgramValueRef | null, outputs?: ProgramValueRef | null, tweak?: JsonValue | null, pinned: boolean, stale: boolean, };

export type ProgramRunPark = { ask_id: string, node_id: string, prompt: string, coordination_stream: string, resume_token: string, };

export type ProgramRunEvent = { sequence: number, node_id: string, kind: ProgramRunEventKind, status?: string | null, cached?: boolean, liveness?: ProcessLiveness | null, refusal_code?: string | null, message?: string | null, value?: ProgramValueRef | null, drained_through_sequence?: number | null, };

export type ProgramRunReceipt = { run_id: string, program_id: string, receipt_id: string, validation: ValidationReceipt, events: Array<ProgramRunEvent>, final_liveness: { [key in string]: ProcessLiveness }, tweak_overlay: { [key in string]: JsonValue }, inspections: { [key in string]: ProgramNodeInspection },
/**
 * Receipts emitted by sandbox runtimes for authored code nodes.
 *
 * The scheduler owns the program receipt while QuickJS and Extism own
 * their execution receipts. Keeping both makes the ring boundary
 * inspectable without teaching this crate how either sandbox works.
 */
runtime_receipts: { [key in string]: JsonValue }, parked?: ProgramRunPark | null, };

export const PROGRAM_CONTRACTS_SOURCE = {
  crate: "rustyred-thg-programmable-graph",
  commit: "84f35a121",
} as const;
