// SOURCING: none — pure logic, no upstream component applies. A build script
// that serializes ./themeModel.ts into the two surfaces the fork already had:
// the TS constant files under src/theme/constants/ and the --t-* CSS layer
// under src/theme-constants/.
//
// Run with `npm run generate:theme`. The generated files are committed so the
// package builds without the generator, exactly as upstream committed theirs.
//
// The CSS variable NAMES are not guessed. They are read out of
// src/theme-constants/themeCssVariables.ts, which is upstream's own accessor
// contract: every leaf there is the string `var(--t-NAME)`, so walking it gives
// the exact name for each theme path. A path present in the accessor but absent
// from the model is a hard failure, which is what keeps a reskin from silently
// dropping a variable a component still reads.

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { themeCssVariables } from '../../theme-constants/themeCssVariables';
import {
  CORNER_SHAPE,
  reg,
  type Mode,
} from './commonplaceTokens';
import {
  buildThemeVariant,
  MAIN_COLOR_ORDER,
  THEME_COMMON_MODEL,
  THEME_COLOR_NAMES,
} from './themeModel';

const here = path.dirname(fileURLToPath(import.meta.url));
const CONSTANTS_DIR = path.resolve(here, '../constants');
const THEME_CONSTANTS_DIR = path.resolve(here, '../../theme-constants');
const PALETTE_DIR = path.resolve(here, './palette');

/**
 * Which palette fills the --t-* layer.
 *
 *   'register' — the original TU2 law: every semantic slot resolves to a
 *     CommonPlace register token, so the fork adopts the console's paint and is
 *     deliberately invisible.
 *   'twenty'   — Twenty's own values, vendored from upstream at the pinned SHA.
 *     The console's --ij-* register then aliases *these* (see
 *     apps/console/src/styles/twenty-register.css), inverting the direction so
 *     Twenty's design language drives the whole app.
 *
 * The law was killed deliberately, not drifted away from. 'register' is kept
 * because the inversion has to stay reversible: one env var returns the fork to
 * resolving against the console register.
 */
const PALETTE: 'twenty' | 'register' =
  process.env.TWENTY_UI_PALETTE === 'register' ? 'register' : 'twenty';

/**
 * Values the fork refuses to take from upstream even under the Twenty palette.
 * `background-noisy` is Twenty's paper texture, inlined as a base64 data URI.
 * TU1 stripped that texture as brand material, and the console's ambient grain
 * is the WebGL MaterialLayer, which a CSS noise layer would paint over.
 */
const PALETTE_REFUSED = new Set(['--t-background-noisy']);

/**
 * Parse a vendored upstream theme file into `--t-name` -> value.
 *
 * Values span lines (gradients, shadows) and can contain semicolons inside
 * `url(data:image/jpeg;base64,...)`, so a declaration ends at the first
 * semicolon that is not nested in parentheses. Splitting naively on `;`
 * truncates that declaration and orphans the rest of the file, which surfaces
 * downstream as a bare "Missing closing }" from the CSS parser.
 */
function loadTwentyPalette(mode: Mode): Map<string, string> {
  const css = fs.readFileSync(path.join(PALETTE_DIR, `twenty-${mode}.css`), 'utf-8');
  const values = new Map<string, string>();
  const nameRe = /(--t-[a-z0-9-_]+):/g;
  let match: RegExpExecArray | null;

  while ((match = nameRe.exec(css)) !== null) {
    let depth = 0;
    let end = -1;
    for (let i = match.index + match[0].length; i < css.length; i += 1) {
      const ch = css[i];
      if (ch === '(') depth += 1;
      else if (ch === ')') depth -= 1;
      else if (ch === ';' && depth === 0) {
        end = i;
        break;
      } else if (ch === '}' && depth === 0) {
        end = i;
        break;
      }
    }
    if (end === -1) continue;
    const name = match[1];
    if (PALETTE_REFUSED.has(name)) continue;
    const value = css.slice(match.index + match[0].length, end).trim().replace(/\s+/g, ' ');
    // Later declarations win, matching the cascade, except that the @supports
    // squircle block must not override the base radii: the console rules round.
    if (!values.has(name)) values.set(name, value);
    nameRe.lastIndex = end;
  }
  return values;
}

const BANNER = `// GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
// Styling truth is CommonPlace tokens; the mapping lives in
// src/theme/generator/themeModel.ts. Run \`npm run generate:theme\`.
`;

const CSS_BANNER = `/* GENERATED by src/theme/generator/emit.ts. Do not edit by hand.
   The --t-* layer every *.module.scss reads. Semantic slots resolve to the
   CommonPlace register (--ij-*) by reference, so the console's light and dark
   registers and its two-knob theme engine reach these components without the
   fork participating. The record palette namespace is derived OKLCH under the
   console's chroma clamp. No upstream color value appears here. */
`;

type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

const isPlainObject = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

/** Serialize a value tree to a TypeScript object literal. */
function serialize(value: unknown, indent = 2): string {
  if (typeof value === 'string') return `'${value.replace(/'/g, "\\'")}'`;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (!isPlainObject(value)) return 'undefined';
  const pad = ' '.repeat(indent);
  const closePad = ' '.repeat(indent - 2);
  const body = Object.entries(value)
    .map(([key, entry]) => {
      const safeKey = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : `'${key}'`;
      return `${pad}${safeKey}: ${serialize(entry, indent + 2)},`;
    })
    .join('\n');
  return `{\n${body}\n${closePad}}`;
}

function writeConstant(fileName: string, exportName: string, value: unknown) {
  const contents = `${BANNER}\nexport const ${exportName} = ${serialize(value)};\n`;
  fs.writeFileSync(path.join(CONSTANTS_DIR, fileName), contents, 'utf-8');
}

/**
 * Walk upstream's accessor map and this fork's theme in lockstep, producing the
 * `--t-NAME: value` pairs. Throws on any path the accessor names and the model
 * does not fill.
 */
function cssDeclarations(
  theme: Record<string, unknown>,
  palette?: Map<string, string>,
): string[] {
  const out: string[] = [];
  const missing: string[] = [];

  const walk = (accessor: unknown, model: unknown, trail: string[]) => {
    if (typeof accessor === 'string') {
      const match = accessor.match(/^var\((--t-[a-z0-9-_]+)\)$/);
      if (match === null) return;
      // In 'twenty' mode the value comes from the vendored upstream palette.
      // The walk itself is unchanged, so the oracle still holds: a name the
      // accessor reads and neither source fills is a hard failure, not a
      // component that silently renders unstyled.
      const fromPalette = palette?.get(match[1]);
      const value = fromPalette ?? model;
      if (value === undefined || value === null) {
        missing.push(`${trail.join('.')} -> ${match[1]}`);
        return;
      }
      out.push(`  ${match[1]}: ${String(value)};`);
      return;
    }
    if (!isPlainObject(accessor)) return;
    for (const [key, child] of Object.entries(accessor)) {
      const next = isPlainObject(model) ? model[key] : undefined;
      walk(child, next, [...trail, key]);
    }
  };

  walk(themeCssVariables, theme, []);

  if (missing.length > 0) {
    throw new Error(
      `Theme model is missing ${missing.length} variable(s) the accessor still reads:\n  ${missing.join('\n  ')}`,
    );
  }
  return out;
}

/** The full theme object for a mode, in the upstream shape. */
function fullTheme(mode: Mode) {
  const variant = buildThemeVariant(mode);
  return {
    ...THEME_COMMON_MODEL,
    // `spacing` is a function on the TS side and a variable ladder on the CSS
    // side. The accessor names spacing-0 through spacing-32 plus the two half
    // steps; the multiplicator stays upstream's 4.
    spacing: spacingLadder(),
    accent: variant.accent,
    background: variant.background,
    blur: variant.blur,
    border: variant.border,
    boxShadow: variant.boxShadow,
    font: variant.font,
    name: mode,
    snackBar: variant.snackBar,
    tag: variant.tag,
    code: variant.code,
    IllustrationIcon: variant.IllustrationIcon,
    grayScale: variant.grayScale,
    color: {
      ...variant.mainColors,
      ...variant.secondaryColors,
      transparent: variant.transparentColors,
    },
  };
}

/** spacing(n) = n * 4px. Upstream's grid, preserved. */
function spacingLadder(): Record<string, string> {
  const ladder: Record<string, string> = {};
  for (let step = 0; step <= 32; step += 1) ladder[String(step)] = `${step * 4}px`;
  ladder['0.5'] = '2px';
  ladder['1.5'] = '6px';
  return ladder;
}

function writeThemeCss(mode: Mode) {
  const selector =
    mode === 'dark'
      ? '.dark,\n[data-register="intui"]'
      : '.light,\n[data-register="intui"][data-theme="light"]';
  const palette = PALETTE === 'twenty' ? loadTwentyPalette(mode) : undefined;
  const declarations = cssDeclarations(
    fullTheme(mode) as Record<string, unknown>,
    palette,
  );
  const contents = [
    CSS_BANNER,
    '',
    `${selector} {`,
    ...declarations,
    // Fork addition. Upstream hardcoded a literal white in Button.module.scss
    // for "ink on a solid accent fill" and called it theme-invariant. It enters
    // through the seam here instead of sitting in a component file. Under the
    // 'twenty' palette it must not reference --ij-*, which now aliases --t-*:
    // that would be a resolution cycle.
    PALETTE === 'twenty'
      ? '  --t-font-color-on-accent: color(display-p3 1 1 1);'
      : `  --t-font-color-on-accent: ${reg('ink-bright')};`,
    // The console's corner ruling: round, not squircle. The MaterialLayer SDF
    // draws circular rounded rects behind each island, and a squircle DOM clip
    // over a circular shader corner is the doubled-corner halo. Upstream's
    // @supports (corner-shape: squircle) block is deliberately not emitted.
    `  --t-corner-shape: ${CORNER_SHAPE};`,
    '}',
    '',
  ].join('\n');
  // A truncated value silently produces a file the CSS parser rejects with a
  // bare "Missing closing }", three layers from the cause. Catch it here.
  for (const declaration of declarations) {
    const open = (declaration.match(/\(/g) ?? []).length;
    const close = (declaration.match(/\)/g) ?? []).length;
    if (open !== close || !declaration.trimEnd().endsWith(';')) {
      throw new Error(
        `Malformed declaration in theme-${mode}.css: ${declaration.trim()}`,
      );
    }
  }
  if (contents.split('{').length !== contents.split('}').length) {
    throw new Error(`Unbalanced braces in theme-${mode}.css`);
  }

  fs.writeFileSync(
    path.join(THEME_CONSTANTS_DIR, `theme-${mode}.css`),
    contents,
    'utf-8',
  );
  return declarations.length;
}

function writeConstantsFor(mode: Mode) {
  const suffix = mode === 'dark' ? 'Dark' : 'Light';
  const upper = mode.toUpperCase();
  const variant = buildThemeVariant(mode);

  writeConstant(`Accent${suffix}.ts`, `ACCENT_${upper}`, variant.accent);
  writeConstant(`Background${suffix}.ts`, `BACKGROUND_${upper}`, variant.background);
  writeConstant(`Blur${suffix}.ts`, `BLUR_${upper}`, variant.blur);
  writeConstant(`Border${suffix}.ts`, `BORDER_${upper}`, variant.border);
  writeConstant(`BoxShadow${suffix}.ts`, `BOX_SHADOW_${upper}`, variant.boxShadow);
  writeConstant(`Code${suffix}.ts`, `CODE_${upper}`, variant.code);
  writeConstant(`Font${suffix}.ts`, `FONT_${upper}`, variant.font);
  writeConstant(`GrayScale${suffix}.ts`, `GRAY_SCALE_${upper}`, variant.grayScale);
  writeConstant(
    `GrayScale${suffix}Alpha.ts`,
    `GRAY_SCALE_${upper}_ALPHA`,
    variant.grayScaleAlpha,
  );
  writeConstant(
    `IllustrationIcon${suffix}.ts`,
    `ILLUSTRATION_ICON_${upper}`,
    variant.IllustrationIcon,
  );
  writeConstant(`MainColors${suffix}.ts`, `MAIN_COLORS_${upper}`, variant.mainColors);
  writeConstant(
    `SecondaryColors${suffix}.ts`,
    `SECONDARY_COLORS_${upper}`,
    variant.secondaryColors,
  );
  writeConstant(`SnackBar${suffix}.ts`, `SNACK_BAR_${upper}`, variant.snackBar);
  writeConstant(`Tag${suffix}.ts`, `TAG_${upper}`, variant.tag);
  writeConstant(
    `TransparentColors${suffix}.ts`,
    `TRANSPARENT_COLORS_${upper}`,
    variant.transparentColors,
  );

  // Colors{suffix}.ts composes the three palette families, exactly as upstream.
  fs.writeFileSync(
    path.join(CONSTANTS_DIR, `Colors${suffix}.ts`),
    `${BANNER}
import { MAIN_COLORS_${upper} } from './MainColors${suffix}';
import { SECONDARY_COLORS_${upper} } from './SecondaryColors${suffix}';
import { TRANSPARENT_COLORS_${upper} } from './TransparentColors${suffix}';

export const COLOR_${upper} = {
  ...MAIN_COLORS_${upper},
  ...SECONDARY_COLORS_${upper},
  transparent: TRANSPARENT_COLORS_${upper},
};
`,
    'utf-8',
  );
}

function writeCommonConstants() {
  // BorderCommon carries the radius law. FontCommon carries the proportions
  // plus the console's UI face. ThemeCommon is upstream's proportions layer
  // with the record metrics pointed at the --rec- group they were extracted to.
  const light = buildThemeVariant('light');
  writeConstant('BorderCommon.ts', 'BORDER_COMMON', {
    radius: (light.border as { radius: unknown }).radius,
  });
  writeConstant('FontCommon.ts', 'FONT_COMMON', {
    size: (light.font as { size: unknown }).size,
    weight: (light.font as { weight: unknown }).weight,
    family: (light.font as { family: unknown }).family,
  });

  fs.writeFileSync(
    path.join(CONSTANTS_DIR, 'ThemeCommon.ts'),
    `${BANNER}
import { ANIMATION } from './Animation';
import { ICON } from './Icon';
import { MODAL } from './Modal';
import { TEXT } from './Text';

export const THEME_COMMON = {
  icon: ICON,
  modal: MODAL,
  text: TEXT,
  animation: ANIMATION,
  spacingMultiplicator: ${THEME_COMMON_MODEL.spacingMultiplicator},
  spacing: (...args: number[]) =>
    args.map((multiplicator) => \`\${multiplicator * 4}px\`).join(' '),
  betweenSiblingsGap: '${THEME_COMMON_MODEL.betweenSiblingsGap}',
  table: {
    horizontalCellMargin: '${THEME_COMMON_MODEL.table.horizontalCellMargin}',
    checkboxColumnWidth: '${THEME_COMMON_MODEL.table.checkboxColumnWidth}',
    horizontalCellPadding: '${THEME_COMMON_MODEL.table.horizontalCellPadding}',
  },
  sidePanelWidth: '${THEME_COMMON_MODEL.sidePanelWidth}',
  clickableElementBackgroundTransition:
    '${THEME_COMMON_MODEL.clickableElementBackgroundTransition}',
  lastLayerZIndex: ${THEME_COMMON_MODEL.lastLayerZIndex},
  buttons: {
    secondaryTextColor: '${THEME_COMMON_MODEL.buttons.secondaryTextColor}',
  },
};
`,
    'utf-8',
  );
}

function main() {
  writeCommonConstants();
  for (const mode of ['dark', 'light'] as const) {
    writeConstantsFor(mode);
    const count = writeThemeCss(mode);
    process.stdout.write(`theme-${mode}.css: ${count} variables\n`);
  }
  process.stdout.write(
    `constants: ${MAIN_COLOR_ORDER.length} main colors, ${THEME_COLOR_NAMES.length} palette names\n`,
  );
}

main();

export type { Json };
