// SOURCING: @jalco/file-tree language tint table. Hex lives in the register lane.
export const FILE_ICON_MAP: Record<string, { color: string; label: string }> = {
  ts: { color: "#3178c6", label: "TS" },
  tsx: { color: "#3178c6", label: "TX" },
  js: { color: "#f7df1e", label: "JS" },
  jsx: { color: "#f7df1e", label: "JX" },
  json: { color: "#a8a8a8", label: "{}" },
  md: { color: "#519aba", label: "M" },
  mdx: { color: "#519aba", label: "MX" },
  css: { color: "#563d7c", label: "#" },
  html: { color: "#e34c26", label: "<>" },
  svg: { color: "#ffb13b", label: "◇" },
  png: { color: "#a074c4", label: "▪" },
  jpg: { color: "#a074c4", label: "▪" },
  gif: { color: "#a074c4", label: "▪" },
  yaml: { color: "#cb171e", label: "Y" },
  yml: { color: "#cb171e", label: "Y" },
  toml: { color: "#9c4121", label: "T" },
  env: { color: "#ecd53f", label: "·" },
  gitignore: { color: "#f05032", label: "G" },
  lock: { color: "#a8a8a8", label: "🔒" },
  sh: { color: "#89e051", label: "$" },
  bash: { color: "#89e051", label: "$" },
  py: { color: "#3572a5", label: "Py" },
  rs: { color: "#dea584", label: "Rs" },
  go: { color: "#00add8", label: "Go" },
}
